### ISSUE TITLE
Error in running example USGS_data.ipynb

### ISSUE THREAD

**Issue by cuill** [oceanmodeling/searvey#113] opened 2023-10-20 20:34 UTC
I got this error when running the example USGS_data.ipynb:

TypeError: Index(...) must be called with a collection of some kind, 'parm_nm' was passed.

The error is from the line:
usgs_stations = usgs.get_usgs_stations()

**Comment by pmav99** [comment] 2023-10-25 06:47
Thank you @cuill  for the report. 

I can't reproduce it though. Are you on the latest version of `searvey`? That being said, USGS is occasionally returning incosistent data. E.g. check here: https://github.com/oceanmodeling/searvey/issues/86

**Comment by SorooshMani-NOAA** [comment] 2023-10-25 14:36
Currently VIMS uses this tool to get USGS data:

https://github.com/heigeo/climata/blob/master/climata/usgs/__init__.py

**Comment by SorooshMani-NOAA** [comment] 2023-10-25 15:03
@cuill I was able to get the stations list in `usgs_stations = usgs.get_usgs_stations()`. In my case the notebook fails due to missing data later in the north east data retrieval section. 

I installed searvey from `conda` by `conda create -n searvey python=3.9 searvey` (I actually used `mamba`), can you try installing searvey like this and see if you still have the issue?

**Comment by cuill** [comment] 2023-10-25 15:41
@SorooshMani-NOAA It works after installing searvey as you suggested. Thanks for the help.

**Comment by SorooshMani-NOAA** [comment] 2023-10-25 15:51
No problem! Please let me know if you run into any other issues with `searvey` as you try it out. For now I close this ticket. I think you were running into some sort of package incompatibility issue.

**Closed by SorooshMani-NOAA** 2023-10-25 15:51 UTC
Labels: usgs
